version: '3'
services:
  admin:
    build: ./ALWIDA_admin
    image: alwida/admin
    ports:
      - 8888:8888
    volumes:
      - ./ALWIDA_admin:/usr/src/app
    environment:
      - TZ=Asia/Seoul
  app_data:
    build: ./ALWIDA_app_data
    image: alwida/app_data
    ports:
      - 5000:5000
    volumes:
      - ./ALWIDA_app_data:/usr/src/app
    environment:
      - TZ=Asia/Seoul
  mariadb:
    build: ./MariaDB
    image: alwida/mariadb
    volumes:
      - ./MariaDB/data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - TZ=Asia/Seoul
      - ALLOW_EMPTY_PASSWORD=no
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
    restart: always
